name: Build Sphinx-API Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Checkout discover utils
        uses: actions/checkout@master
        with:
            repository: hcmlab/discover-utils
            path: discover-utils
            ref: refs/heads/main    
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst-parser
      - name: Sphinx build
        run: |
          sphinx-build discover-utils/docs/docsource _build
          sphinx-build docs/docsource _build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
